apiVersion: v1
kind: Service
metadata:
  name: engines-svc
  namespace: playground
spec:
  type: ClusterIP
  selector:
    app: engines-pod
  ports:
  - name: thrift-server
    protocol: TCP
    port: 10015
    targetPort: 10015
  - name: hive-metastore
    protocol: TCP
    port: 9083
    targetPort: 9083
  - name: hive
    protocol: TCP
    port: 10000
    targetPort: 10000

