apiVersion: v1
kind: Pod
metadata:
  name: engines
  namespace: playground
  labels:
    app: engines-pod
spec:
  containers:
  - name: engines
    image: datalab:latest
    imagePullPolicy: Never
    command: ["bash"]
    args: ["/home/datalab/entrypoint.sh"]
    ports:
    - containerPort: 10000
    - containerPort: 9083
    - containerPort: 10015
    volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    configMap:
      name: cluster-config
      items:
      - key: "config.json"
        path: "config.json"
