apiVersion: v1
kind: Service
metadata:
  name: hue-svc
  namespace: playground
spec:
  type: NodePort
  selector:
    app: hue-pod
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30007
